[build]
publish = "build"
command = "yarn build"
functions = "functions/"

[build.environment]
  NODE_VERSION = "20.14.0"
  NPM_VERSION = "10.8.1"

# Redirects for routing
[[redirects]]
  from = "/latestversion"
  to = "/.netlify/functions/latestversion"
  status = 200
  force = true # Always redirect
